### PR TITLE
Feat/wow scan inputs

### LINKED ISSUE #110: add more filters for wow search
ref https://github.com/ff14-advanced-market-search/Aetheryte/pull/100

we added data on items and now are going to let users pick a minimum `itemQuality`, `required_level`, `item_class`, `item_subclass` and `ilvl` (for reference in wow ilvl means item level higher ilvl means better stats)

All 5 of these will be ints. `-1` will be the default value and just return everything. 

Heres an example of the new api call this one is allowing all other filters and just looks for items that are rare or better. 
```
 {
    "homeRealmId": 61,
    "newRealmId": 3678,
    "min_historic_price": 10000,
    "desired_roi": 50,
    "sale_per_day": 0,

    "itemQuality": 3,
    "required_level": -1,
    "item_class": -1,
    "item_subclass": -1,
    "ilvl": -1
}
```
____

# what these values mean 

`required_level` and `ilvl` can be any value.  Note the lowest this goes is 0 so -1 returns everything.  Anything above that level is returned. 

For the `item_class` and `item_subclass` these are the wow categories:
https://wowpedia.fandom.com/wiki/ItemType

Right now its just one subclass and class we cant do multiple ones yet but it works the same as ffxiv.  Eventually we can make these lists. 

For `itemQuality` the menu we design should basically pick an int based on one of these values [(more info here)](https://wowpedia.fandom.com/wiki/Quality).  For example picking `Uncommon` will only return green items or better. 

```
        item_qualities = {
            "Poor": 0,
            "Common": 1,
            "Uncommon": 2,
            "Rare": 3,
            "Epic": 4,
            "Legendary": 5,
            "Artifact": 6,
            "Heirloom": 7,
        }
```

### PR DESCRIPTION
**Pull request by oldben87**
## Why

Add new form fields for the WoW scan

## Related Tickets

* Closes #110 

## Considerations

Additional context/info.

### CODE REVIEW

**Comment by cohenaj194** [comment]
@oldben87 can you try out a ffxiv search? the api is responding but something is breaking on the fe https://feat-wow-scan-inputs.saddlebag-with-pockets.pages.dev/queries/full-scan

**Comment by oldben87** [comment]
Is it because we changed the cluster config?

**Comment by cohenaj194** [comment]
> @cohenaj194 Is it because we changed the cluster config?

No something is just wrong with the changes to the ffxiv stuff.  Can you take out all ffxiv changes lets move it to a new pr.

**Comment by cohenaj194** [comment]
Nevermind I think the test container we had was behind a commit from dev im fixing it now

**Review by cohenaj194 — APPROVED** [review]

**Pull request merged**
